package com.astraedus.nudge.data.db.entity

/**
 * The identity of a [UsageEvent] for import de-duplication -- everything about the event EXCEPT its
 * local row id, which is autogenerated per device and therefore meaningless across a restore.
 *
 * `blockMode` is deliberately NOT part of the key: it is descriptive rather than identifying (the
 * same confrontation cannot have happened twice in the same millisecond under two modes), and
 * including it would let a mode rename silently duplicate a user's whole history on re-import.
 *
 * Doubles as a Room projection so the dedup pass can read four columns instead of whole rows.
 */
data class UsageEventKey(
    val packageName: String,
    val timestamp: Long,
    val wasBlocked: Boolean,
    val userChangedMind: Boolean
)
